#!/bin/bash

# Get the current branch name
gitbranch=$(git rev-parse --abbrev-ref HEAD)

# Get the current timestamp
timestamp=$(date +"%Y-%m-%d %H:%M:%S")

# Get the current commit hash
githash=$(git rev-parse HEAD)

# Run the command with variables substituted
post_status/$DeNa/git/$gitbranch $timestamp:$githash

# Exit with success code
exit 0 
